### ISSUE TITLE
how to use SGRAF?

### ISSUE THREAD

**Issue by iTomxy** [QinYang79/DECL#3]
Hi, I wonder how do you use the SGRAF backbone? Seems that in [SGRAF.py](https://github.com/QinYang79/DECL/blob/main/2022-ACMMM-DECL/model/SGRAF.py), only `SGR` and `SAF` are supported, while the default `AVE` is not supported. I guess the `AVE` means SGRAF? Thanks.

**Comment by QinYang79** [comment]
Like standard SGRAF, DECL-SAF and DECL-SGR are trained independently. DECL-SGRAF means that the similarities used for retrieval are the average results of similarities inferred by the two models.

**Comment by iTomxy** [comment]
Got it. Thanks
